# Generated by Django 3.2 on 2022-02-26 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0005_auto_20220223_2139'),
        ('profiles', '0002_userlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='works.production'),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
