# Generated by Django 3.2 on 2022-05-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_donation_donation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_number',
            field=models.CharField(default='CAE5F9059D46417F915C69E007B01152', max_length=32),
        ),
    ]
