# Generated by Django 3.2 on 2022-05-23 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0005_alter_donation_donation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_number',
            field=models.CharField(default='CAE522D8B2B640838CD92FFCC8AF1674', max_length=32),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
