# Generated by Django 3.2 on 2022-05-23 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0014_alter_productionvideo_youtube_source'),
        ('donations', '0007_auto_20220523_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.production'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_number',
            field=models.CharField(default='1F3754C0D692446F8F652CF333CE3769', max_length=32),
        ),
    ]
