# Generated by Django 3.2 on 2022-05-24 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_auto_20220523_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
