# Generated by Django 3.2 on 2022-05-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_alter_donation_donation_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='street_address2',
        ),
    ]
