# Generated by Django 3.2 on 2022-02-04 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('synopsis', models.TextField()),
                ('tagline', models.CharField(max_length=254)),
                ('hash_tag', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=100)),
                ('composer', models.CharField(max_length=100)),
                ('librettist', models.CharField(max_length=100)),
                ('world_premiere', models.DateField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('hero_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('thumb_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumb_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('record_added', models.DateTimeField(auto_now_add=True)),
                ('record_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('production_premiere', models.DateField()),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('set_designer', models.CharField(blank=True, max_length=100, null=True)),
                ('costume_designer', models.CharField(blank=True, max_length=100, null=True)),
                ('lighting_designer', models.CharField(blank=True, max_length=100, null=True)),
                ('relighter', models.CharField(blank=True, max_length=100, null=True)),
                ('choreographer', models.CharField(blank=True, max_length=100, null=True)),
                ('producer', models.CharField(blank=True, max_length=100, null=True)),
                ('dead', models.BooleanField(blank=True, default=False, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('hero_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('thumb_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumb_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('record_added', models.DateTimeField(auto_now_add=True)),
                ('record_edited', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.work')),
            ],
        ),
    ]
