# Generated by Django 3.2 on 2022-04-17 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(max_length=254)),
                ('tagline', models.CharField(blank=True, max_length=254, null=True)),
                ('facebook', models.SlugField(blank=True, max_length=254, null=True)),
                ('twitter', models.SlugField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('hero_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('thumb_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('record_added', models.DateTimeField(auto_now_add=True)),
                ('record_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(max_length=254)),
                ('year', models.PositiveSmallIntegerField()),
                ('synopsis', models.TextField()),
                ('tagline', models.CharField(max_length=254)),
                ('hash_tag', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=100)),
                ('production_premiere', models.DateField()),
                ('dead', models.BooleanField(blank=True, default=False, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumb_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('record_added', models.DateTimeField(auto_now_add=True)),
                ('record_edited', models.DateTimeField(auto_now=True)),
                ('rating_total', models.PositiveIntegerField(blank=True, null=True)),
                ('rating_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('composer', models.CharField(max_length=100)),
                ('librettist', models.CharField(max_length=100)),
                ('world_premiere', models.DateField()),
                ('hero_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('thumb_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('record_added', models.DateTimeField(auto_now_add=True)),
                ('record_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('record_added', models.DateTimeField(auto_now_add=True)),
                ('record_edited', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='works.people')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'photo'), ('V', 'video'), ('F', 'pdf')], max_length=1)),
                ('url', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('thumb_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('record_added', models.DateTimeField(auto_now_add=True)),
                ('record_edited', models.DateTimeField(auto_now=True)),
                ('rating_total', models.PositiveIntegerField(blank=True, null=True)),
                ('rating_count', models.PositiveIntegerField(blank=True, null=True)),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.production')),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='cast', to='works.Role'),
        ),
        migrations.AddField(
            model_name='production',
            name='creatives',
            field=models.ManyToManyField(blank=True, related_name='creatives', to='works.Role'),
        ),
        migrations.AddField(
            model_name='production',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staff', to='works.Role'),
        ),
        migrations.AddField(
            model_name='production',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.work'),
        ),
    ]
