# Generated by Django 3.2 on 2022-02-22 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='url',
            field=models.SlugField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
