# Generated by Django 3.2 on 2022-02-12 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='url',
            field=models.SlugField(max_length=254),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'photo'), ('V', 'video'), ('F', 'pdf')], max_length=1)),
                ('url', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('thumb_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumb_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('record_added', models.DateTimeField(auto_now_add=True)),
                ('record_edited', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.production')),
            ],
        ),
    ]
