# Generated by Django 3.2 on 2022-02-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_production_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='cast', to='works.Role'),
        ),
        migrations.AlterField(
            model_name='production',
            name='creatives',
            field=models.ManyToManyField(blank=True, related_name='creatives', to='works.Role'),
        ),
        migrations.AlterField(
            model_name='production',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staff', to='works.Role'),
        ),
    ]
