# Generated by Django 3.2 on 2022-02-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20220212_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='ProductionMedia',
        ),
    ]
