# Generated by Django 3.2 on 2022-02-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20220222_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='tagline',
            field=models.CharField(default='asdfdsfdsfsdf', max_length=254),
            preserve_default=False,
        ),
    ]
