# Generated by Django 3.2 on 2022-02-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_rename_media_productionmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(max_length=254)),
                ('facebook', models.SlugField(blank=True, max_length=254, null=True)),
                ('twitter', models.SlugField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('synopsis', models.TextField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('hero_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('thumb_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumb_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('record_added', models.DateTimeField(auto_now_add=True)),
                ('record_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
