# Generated by Django 3.2 on 2022-02-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_people_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='tagline',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
