# Generated by Django 3.2 on 2022-05-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20220517_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='hero_image_url',
        ),
        migrations.RemoveField(
            model_name='work',
            name='librettist',
        ),
        migrations.RemoveField(
            model_name='work',
            name='thumb_image_url',
        ),
        migrations.AlterField(
            model_name='work',
            name='composer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='works.people'),
        ),
    ]
