# Generated by Django 3.2 on 2022-02-14 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='director',
        ),
    ]
