# Generated by Django 3.2 on 2022-05-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20220518_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='composer',
            new_name='composer_name',
        ),
    ]
