# Generated by Django 3.2 on 2022-02-14 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_remove_production_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.people'),
        ),
    ]
