# Generated by Django 3.2 on 2022-05-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_rename_composer_work_composer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='composer_name',
        ),
    ]
