# Generated by Django 3.2 on 2022-05-18 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_remove_work_composer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='composer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='works.people'),
            preserve_default=False,
        ),
    ]
