# Generated by Django 3.2 on 2022-05-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0011_auto_20220518_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='facebook',
            field=models.SlugField(blank=True, help_text='Only the username portion of the URL', max_length=254, null=True, verbose_name='Facebook username'),
        ),
        migrations.AlterField(
            model_name='people',
            name='twitter',
            field=models.SlugField(blank=True, help_text='Only the username portion of the URL (no @ or #)', max_length=254, null=True, verbose_name='Twitter username'),
        ),
        migrations.AlterField(
            model_name='people',
            name='url',
            field=models.SlugField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='url',
            field=models.SlugField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='url',
            field=models.SlugField(max_length=254, unique=True),
        ),
    ]
