# Generated by Django 3.2 on 2022-05-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_auto_20220518_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionvideo',
            name='youtube_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productionvideo',
            name='source',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
